[package]
name = "catenary-tdx-data"
version = "0.1.0"
edition = "2021"

[dependencies]
iso8601 = "0.6.1"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.1", features = ["full"] }
