[package]
name = "catenary-tdx-data"
version = "0.1.0"
edition = "2021"

[dependencies]
iso8601 = "0.6.1"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.118"
tokio = { version = "1.37.0", features = ["full"] }
